<ul class="nav nav-pills">
    <li role="presentation"><a href="/dashboard">Home</a></li>
    <li role="presentation" class="active"><a href="/dashboard/prizes">Prizes</a></li>
    <li role="presentation"><a href="/dashboard/trigger">Trigger Giveaway</a></li>
</ul>
<?php
$title = 'Avaliable Prizes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('dashboard', array('action'=>'addPrize'));?>">Add new prize</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Distributed</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($prizes as $prize) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($prize->name);?></td>
            <td><?php echo ($prize->available == 1) ? 'NO' : 'YES';?></td>
            <td>
                <?php if($prize->available == NULL): ?>
                <a href="<?php echo $this->url('dashboard',
                    array('action'=>'editPrize', 'id' => $prize->id));?>">Edit</a>
                <a href="<?php echo $this->url('dashboard',
                    array('action'=>'deletePrize', 'id' => $prize->id));?>">Delete</a>
            <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>